### ISSUE TITLE
pcmake.ttp: pcc.ttp: No such file or directory

### ISSUE THREAD

**Issue by mikrosk** [th-otto/pcmake#2]
I've found some time to play with this tool. I started with the crosstos binaries but quickly switched into native (aranym) environment because I couldn't get it working reliable. And I still can't. ;)

Basically no matter what I do, https://github.com/th-otto/pcmake/blob/master/exec.c#L383 is failing on me. What I do:

- downloaded latest aranym/freemint snapshot
- opened toswin2
- set $PATH to point to `pcc.ttp` (in the end I put it into `/bin` but no help there either)
- went into some pure c project, invoked as `pcmake.ttp -v <project name.prj`
- saw the first file compiling
- terminated by the Pexec() error code

I even tried to replace `env` with `NULL` but again, same result. Also made `pcc.ttp` executable on the host, didn't help either.

Am I missing something obvious here? I don't believe that FreeMiNT's Pexec() stopped working out of the sudden.

**Comment by th-otto** [comment]
Where is your pcmake.ttp located? It normally should be in the same directory as pcc.ttp, with lib and include being subdirectories of it.

With that, i don't get errors from Pexec here. However there seems to be indeed some problems running in mint. It does not find the libraries and include directory. Maybe that can be worked around by using absolute paths for them in the project file.

For my automated builds i use an image using emutos and gemini/mupfel: https://tho-otto.de/download/mag-hdd.tar.bz2

Maybe you can try that?

**Comment by mikrosk** [comment]
Mupfel I tried just before that -- and since it didn't work I was like OK, maybe fork() is not really well behaving in TOS? So you see, now I'm really desperate. :-P

(`pcmake.ttp` was put into Pure C's directory and I can launch it without specifying absolute path so it's even more suspicious why Pexec is failing / not finding `pcc.ttp`)

If / when you have time, maybe you can try my simple scenario from above: just latest snapshot, pure_c directory and some prj file.

**Comment by mikrosk** [comment]
Hmm I see that you are using an actual _image_ ... maybe this has something to do with hostfs?

**Comment by th-otto** [comment]
> maybe fork() is not really well behaving in TOS? 

fork() doesn't work in TOS, that's why pcmake uses Pexec directly.

> (`pcmake.ttp` was put into Pure C's directory and I can launch it without specifying absolute path so it's even more suspicious why Pexec is failing / not finding `pcc.ttp`)

If pcmake is found using the $PATH and they are in the same directory, then pcc.ttp should be found too. But apparently it isn't. Maybe has to do with ``$PATH`` not being transformed by the startup code (Pure-C does not use mintlib). When it is not found, then it is executed as just plain "pcc.ttp", without a path. That is where you get the error from.
Similar, argv[0] might be a mint path when run from toswin2/bash. That's why pcmake does not find its own path.

> If / when you have time, maybe you can try my simple scenario from above: just latest snapshot, pure_c directory and some prj file.

Currently i'm busy with other things, but i'll have a look.

> Hmm I see that you are using an actual image ... maybe this has something to do with hostfs?

No it does not rely on hostfs, this does not exist without mint. The image is primarily used for building https://github.com/th-otto/MagicMac (hence its name). There i use mtools to copy the sources to the image, before starting aranym. If you use the config file from the archive, it should drop you into a mupfel shell. ``exit`` will get you back to the EmuTOS desktop.


![Screenshot_20230912_113520](https://github.com/th-otto/pcmake/assets/12425871/e46c298d-b546-459d-ae02-08791b927b34)

**Comment by th-otto** [comment]
Invoking pcmake.ttp with a full path like ``/c/pc/pcmake.ttp`` should help (unlike mupfel, bash only passes the name from the commandline as argv[0], not the full name where it was found)

But i've also pushed a fix for it.

**Comment by mikrosk** [comment]
Interesting, I wonder why it failed in Mupfel for me then. Nevertheless, now it seems fixed at least in bash, so thanks for that!

**Comment by th-otto** [comment]
Maybe because of different setting of ``$TOSDEFAULT``.

(sorry only have german documentation about this)
```
#   m: Maus anschalten?
#   c: Textcursor einschalten?
#   b: Hintergrund grau?
#   s: Argumente auch mit shel_write Ã¼bergeben?
#   d: Vor AusfÃ¼hrung in Programm-Verzeichnis wechseln?
#   w: Sollen TOS-Programme im Console-Window laufen?
#   x: Das ARGV-Verfahren benutzen?
#   k: Nach Programmende auf Tastendruck warten?
#   o: Programm als Overlay starten?
#   l: Cursor-Blinken einschalten? (FÃ¼r TOS-Programme)
#   i: Programm lÃ¤uft im Single-Modus von Mag!X
```

At home, i have
```
TOSDEFAULT="M:N,C:Y,B:N,S:N,D:N,W:Y,X:Y,K:N"
GEMDEFAULT="M:Y,C:N,B:Y,S:Y,D:N,W:Y,X:Y,K:N"
```

i think that are also the settings in the profile on on the harddisk image.

**Comment by mikrosk** [comment]
That was a *great* hint, thanks! Indeed the `TOSDEFAULT` made the difference. What is even better, `pclink.ttp` works in Hatari + Mupfel with many object files. In bash I got `linking failed: 2560` and when entered the command line manually (with `\` -> `/`) I got ... a bus error.

I would expect that bash passes the command line also via ARGV?

**Comment by th-otto** [comment]
Yes, bash uses mintlib, and that will always use ARGV. mupfel does it only when X:Y is set. And of course the link commandline is the one which is most likely won't fit in 126 characters.

pclink is itself compiled using pure-c, so most likely does not handle '/' in filenames. pcmake will convert them before invoking it, but if you run it directly from bash, you have to use '\\' and quote them.

**Comment by mikrosk** [comment]
But still, that wouldn't explain why it is failing in bash when invoking by `pcmake` -- that's when I see that mysterious 2560 error code.

**Comment by th-otto** [comment]
Hm, can't reproduce that:
```
$ pcmake keytest.prj
pcmake: processing U:\c\src\test\keytest.prj
u:\c\pc\pcc.ttp -G -K -L64 -M -I..\include\ -Iu:\c\pc\include -Okeytest.o keytest.c
u:\c\pc\plink.ttp -S=12000 -O=keytest.tos u:\c\pc\lib\cstartv.o keytest.o u:\c\pc\lib\pcgemlib.lib u:\c\pc\lib\pcstdlib.lib u:\c\pc\lib\pctoslib.lib
```

No error code or crash.

Also works running pcmake on its own project file, where the linker commandline is too long when not using ARGV.

**Comment by mikrosk** [comment]
Hmm, the only difference I see is that I had just `-Ooutput.o` there with tens of `folder\obj.o` files, i.e. somewhat longer than yours.

**Comment by th-otto** [comment]
Can you point me to the source you are trying to compile? I only see references to pcmake above.

**Comment by mikrosk** [comment]
I've sent you a minimal repro on your email as the source code is not yet public. :)

**Comment by mikrosk** [comment]
Ok, it turned out to be a memory protection issue.

**Comment by th-otto** [comment]
Yes, exitcode 2560 is actually 256 * SIGBUS so it seems plink is killed by it. I can reproduce it now, however i don't see any alertbox or anything else, so i don't even know where it crashes. 

But its strange. When i run manually
```
/c/pc/plink.ttp -J -O=predmety.o 'domy\dum1.o' \
	'domy\dum2.o' 'domy\statek.o' 'domy\kostel.o' \
	'domy\hran1.o' 'domy\hran2.o' 'domy\tezvez.o' \
	'domy\dumpo1.o' 'domy\dumpo2.o' 'domy\mesita.o' \
```
it works (the commandline is already longer than 126 chars)

But when i add another filename, it crashes.

**Comment by mikrosk** [comment]
I had come to a similar conclusion, couldn't find a pattern in it so I left it as is. Perhaps there's a `#define` in the source for some buffer size and this overflows. But the fact that aranym runs it is alone a great win for performance.

**Comment by th-otto** [comment]
I think i found it. It was accessing only 1 byte beyond an (empty) symbol name. Attached is a fixed version that now also worked in your project with aranym+mmu (of course that does not mean there are no other places where that could happen, too).

BTW, i found that by compiling plink for linux, and run that under valgrind ;)

PS.: when creating libraries with -J, you should also name them .lib, not .o. There are some places where files are treated differently depending on extension.

[plink.zip](https://github.com/th-otto/pcmake/files/12640267/plink.zip)

**Comment by mikrosk** [comment]
Amazing, it really works well now. Many thanks. At one point I saw the same error but now if I run the whole prj chain everything compiles and links smoothly so most like it is as you say -- there can be other invalid memory access hidden.

This tool is really a life saver!
