### ISSUE TITLE
Suggestion: process first found PRJ is no argument given ?

### ISSUE THREAD

**Issue by vinz6751** [th-otto/pcmake#6]
Hi
Thank you again for PCMAKE which I use very often with my Foenix A2560U :)
I invoking it from MicroEmacs and it's repetitive to specify "-f whatever.prj" every time.
I was wondering what you think about the idea that PCMAKE, if no argument given, would try to use "any" PRJ it finds in the current directory ? That's what "make" does, as it tries to use any present "Makefile". So it wouldn't be so weird PC*MAKE* to act in a similar way ;)
I did an awful hack to do this, but I think you could come up with something more elegant.

```
@@ -229,10 +229,18 @@ int main(int argc, const char **argv)
                print_usage(false);
        } else if (prj_name == NULL && argc != 1)
        {
-               print_usage(true);
-               err = EXIT_FAILURE;
+               // Find the first PRJ (order is unspecified) in the folder and if found, build it
+               if (Fsfirst("*.prj",0) == 0) {
+                       prj_name  = dta.dta_name;
+                       goto gut;
+               } else
+               {
+                       print_usage(true);
+                       err = EXIT_FAILURE;
+               }
        } else
        {
+       gut:
                errout_nfdebug = makeopts.nfdebug;
 
                if (prj_name == NULL)
```

**Comment by th-otto** [comment]
Done now. Though i could not use the simple patch above, because
- Fsfirst is only for TOS, but the program can also be compiled on linux, where it will use the crosstos binaries.
- The directory has to be changed *before* doing the lookup of the project file
- I also added a check that really only a single project is found, since otherwise it is unpredictable which one will be used.

**Comment by vinz6751** [comment]
Thank you very much ! :) I don't know what crosstos, I'll need to find out!

**Comment by th-otto** [comment]
https://bitbucket.org/pep-entral/crosstos/src/master/
